import Link from 'next/link'
import { HeroVisual } from './HeroVisual'

// Vertical rhythm is tight (and partly vh-based) so headline → visual fills
// one desktop screen; `.hero-stage` in globals.css sizes the visual to fit.
export function Hero() {
  return (
    <section className="hero-fill relative overflow-hidden lg:flex lg:flex-col">
      {/* The visual scales in steps, so up to ~40px of screen is left over below it;
          where `.hero-fill` stretches the section to the screen, this spacer takes
          that leftover (max 48px) so the visual ends at the fold. */}
      <div aria-hidden="true" className="hidden lg:block grow max-h-12" />

      <div className="max-w-6xl mx-auto px-4 sm:px-6 pt-[clamp(28px,6vh,64px)] text-center">
        {/* `!` — the unlayered h1–h6 rule in globals.css otherwise wins over utilities */}
        <h1 className="hero-rise font-serif font-[400]! text-[length:clamp(40px,min(5.6vw,8.8vh),72px)] leading-[1.08]! text-[#0f1012] text-balance">
          Studio-Ready Fashion <br className="hidden sm:block" />
          From a Single Photo
        </h1>

        <p className="hero-rise [--d:80ms] mt-3 max-w-[540px] mx-auto text-[16px] sm:text-[18px] leading-[1.55] tracking-[-0.015em] text-[#0f1012]/60 text-balance">
          Ghost mannequin shots, sewing patterns and virtual try-ons — generated by AI in under 90 seconds, no studio required.
        </p>

        <div className="hero-rise [--d:160ms] mt-6 flex items-center justify-center gap-2 sm:gap-3">
          <Link
            href="/register"
            className="inline-flex items-center justify-center h-11 sm:h-12 px-4 sm:px-7 max-[359px]:px-3 rounded-full bg-[#0f1012] text-[14px] sm:text-[15px] max-[359px]:text-[13px] tracking-[-0.01em] whitespace-nowrap text-[#faf9f5] hover:bg-[#2a2c30] transition-colors"
          >
            Start Designing Free
          </Link>
          <a
            href="#how-it-works"
            className="inline-flex items-center justify-center h-11 sm:h-12 px-4 sm:px-7 max-[359px]:px-3 rounded-full border border-[#0f1012] text-[14px] sm:text-[15px] max-[359px]:text-[13px] tracking-[-0.01em] whitespace-nowrap text-[#0f1012] hover:bg-[#0f1012] hover:text-[#faf9f5] transition-colors"
          >
            See How It Works
          </a>
        </div>
      </div>

      <div className="mt-3">
        <HeroVisual />
      </div>
    </section>
  )
}
